### ISSUE TITLE
有没有完善项目的计划

### ISSUE THREAD

**Issue by zh-h** [phodal/winv#2]
我觉得这个想法很有前途

**Comment by phodal** [comment]
@zh-h 现在有点博弈的感觉，如果 MINA 开源了这个项目就没有存在的意义，如果 MINA 不开源，这有必要进行这个项目。现在，是要做一些基本的技术储备，具体规划估计要等国庆后。

**Comment by zhaoweijing2003** [comment]
用这个框架实现了一个按钮的点击事件，但是发现点击事件是在加载之后立即执行了，页面展示完毕之后，没有任何交互性。但是还是非常赞的，基本上搞清楚了微信小程序的运行流程

**Comment by phodal** [comment]
@ zhaoweijing2003 棒棒的，其实现在就少一个事件系统

**Comment by zhaoweijing2003** [comment]
@phodal 嗯，看你得博客，之前提到微信小程序里面有两套事件循环机制。我觉得微信小程序比react-redux编写起来舒服多了，redux冗余的东西太多了。小程序干净清爽

**Comment by phodal** [comment]
@zhaoweijing2003 不过，微信小程序很多复杂的功能是不用做的
